### ISSUE TITLE
Add to alley order a product which has been selected from the catalog

### ISSUE THREAD

**Issue by Danny-7** [AurelDP/BowlingOrdersManager#3]
Goal: Add to the alley order a product (it creates order items) linked to an alley

The endpoint method should be `POST` on this endpoint path `/cart?qrCode=`

The qrCode is the unique identifier of the alley

In the payload request, we should have those following properties

- productId
- quantity

- [ ] In addition

When adding to the alley order, we should update the product catalog inventory, by removing the quantity given in the request.
In this case we assume, the quantity is not overpassing the quantity of the product catalog

**Comment by antoinedespres** [comment]
To do : function to map a qr code to its alley id

**Comment by antoinedespres** [comment]
Done
